export enum EnumListaServico {
	enviarNotificacao = 1,
	migrarDados = 2,
	criarUsuario = 3,
	atribuirPerfilUsuario = 4,
	comunicarSituacaoAtualCadastro = 5,
	comunicarSituacaoAtualPmn = 6,
	disponibilizarDadosPorCnpj = 7,
	disponibilizarDadosPorCpf = 8,
	disponibilizarDadosPorInscricaoCadastral = 9,
	enviarDadosPmn = 10,
	atualizarSituacaoCredenciamento = 11,
	atualizarSituacaoInscricao = 12,
	obterDadosUsuarioLogado = 13,
	obterDadosUsuarioPorUnidadeESetor = 14,
	receberBloqueioDesbloqueoCadastro = 15,
	receberBloqueioSac = 16,
	receberDesbloqueioSac = 17,
	receberInscricaoSuframaAuditor = 18,
	receberLiquidacaoDebitoSac = 19,
	recuperarPerfilUsuarioLogado = 20,
	registrarDebitoSac = 21,
	atualizarSituacaoProtocolo = 22,
	reenviarGeracaoDebito = 23,
	distribuicaoAutomaticaProtocolos = 24,
}
