export enum EnumTipoRequerimento {
	inscricaoCadastralPessoaJuridica = 1,
	atualizacaoInscricaoCadastralPessoaJuridica = 2,
	atualizacaoDocumentosPessoaJuridica = 3,
	reativacaoInscricaoCadastralPessoaJuridica = 4,
	cancelamentoInscricaoCadastralPessoaJuridica = 5,
	enviarRecursoPessoaJuridica = 6,
	desbloqueioPessoaJuridica = 7,
	inscricaoCadastralPessoaFisica = 8,
	atualizacaoInscricaoCadastralPessoaFisica = 9,
	atualizacaoDocumentosPessoaFisica = 10,
	reativacaoInscricaoCadastralPessoaFisica = 11,
	cancelamentoInscricaoCadastralPessoaFisica = 12,
	enviarRecursoPessoaFisica = 13,
	desbloqueioPessoaFisica = 14,
	credenciamentoPessoaJuridicaAuditor = 15,
	atualizacaoCredenciamentoPessoaJuridicaAuditor = 16,
	credenciamentoPessoaJuridicaTransportador = 17,
	atualizacaoCredenciamentoPessoaJuridicaTransportador = 18,
	credenciamentoPessoaJuridicaRemetente = 19,
	atualizacaoCredenciamentoPessoaJuridicaRemetente = 20,
	credenciamentoPessoaFisicaPreposto = 21,
	atualizacaoCredenciamentoPessoaFisicaPreposto = 22,
	credenciamentoPessoaFisicaConsultor = 23,
	atualizacaoCredenciamentoPessoaFisicaConsultor = 24,
	credenciamentoPessoaFisicaTransportador = 25,
	atualizacaoCredenciamentoPessoaFisicaTransportador = 26,
}
