export enum EnumStatusProtocolo {
	gerado = 1,
	aguardandoPagamento = 2,
	prontoParaAnalise = 3,
	pagamentoRecebido = 4,
	aguardandoAnalise = 5,
	emAnalise = 6,
	comPendencia = 7,
	aguardandoConferenciaDocumental = 8,
	aguardandoReanalise = 9,
	aguardandoVisitaTecnica = 10,
	deferido = 11,
	indeferidoAguardandoRecurso = 12,
	cancelado = 13,
	recursoEmAnalise = 14,
	indeferido = 15,
	emJulgamento = 16,
}
