namespace Suframa.Sciex.CrossCutting.DataTransferObject.Enum
{
    public enum EnumMensagemErro
	{
		INSCRICAO_CADASTRAL_EMPRESA = 500,
		DI_DUPLICADA = 501,
		QUANTIDADE_ADICOES_DIVERGENTE = 502,
		DATA_REGISTRO_INVALIDA = 503,
		DATA_DESEMBARAÇO_INVALIDA = 504,
		CODIGO_URF_ENTRADA_NAO_CADASTRADO = 505,
		CODIGO_URF_DESPACHO_NAO_CADASTRADO = 506,
		LI_NAO_ENCONTRADA = 507,
		LI_STATUS_INVALIDO = 508,
		CODIGO_FUNDAMENTACAO_LEGAL_NAO_CADASTRADO = 509
	}
}