namespace Suframa.Sciex.CrossCutting.DataTransferObject.Enum
{
    public enum EnumPliStatus
    {
		NÃO_ANALISADO = 0,
		ANALISE_OK_NA_SUFRAMA =	1,
		ANALISE_VISUAL = 2, 
		ANALISE_COM_ERRO_NA_SUFRAMA = 3,
		ANALISE_VISUAL_P_EMPRESA_NOVA = 5,
		ANALISE_VISUAL_P_EMPRESA_COMERCIAL = 6,
		ANALISE_VISUAL_OK_NA_SUFRAMA = 7,
		ANALISE_VISUAL_COM_ERRO_NA_SUFRAMA = 8,
		ANALISE_VISUAL_PENDENTE = 9,
		ANALISE_VISUAL_P_LI_REFERENCIA_SUBSTITUIDA = 10,
		PENDENTE = 19,
		EM_ELABORAÇÃO = 20,
		ENTREGUE = 21,
		AGUARDANDO_GERAÇÃO_DE_DÉBITO = 22,
		AGUARDANDO_ANÁLISE_VISUAL = 23,
		AGUARDANDO_PROCESSAMENTO = 24,
		PROCESSADO = 25
    }
}