//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suframa.Sciex.CrossCutting.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Suframa.Sciex.CrossCutting.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Existe um protocolo em andamento vinculado ao seu CPF. Favor aguardar a conclusão ou cancelamento do mesmo para dar continuidade a sua solicitação..
        /// </summary>
        public static string AGUARDAR_FINALIZAR_PROTOCOLO {
            get {
                return ResourceManager.GetString("AGUARDAR_FINALIZAR_PROTOCOLO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Existe um protocolo em andamento vinculado ao seu CNPJ. Favor aguardar a conclusão ou cancelamento do mesmo para dar continuidade a sua solicitação..
        /// </summary>
        public static string AGUARDAR_FINALIZAR_PROTOCOLO_PJ {
            get {
                return ResourceManager.GetString("AGUARDAR_FINALIZAR_PROTOCOLO_PJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Alteração realizada com sucesso..
        /// </summary>
        public static string ALTERAÇÃO_REALIZADA_COM_SUCESSO {
            get {
                return ResourceManager.GetString("ALTERAÇÃO_REALIZADA_COM_SUCESSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {{&gt; style}}
        ///&lt;div class=&quot;text-center&quot; style=&quot;width:100%&quot;&gt;
        ///	&lt;table&gt;
        ///		&lt;tbody&gt;
        ///
        ///			{{&gt; notificacaoCabecalho}}
        ///
        ///			&lt;tr&gt;
        ///				&lt;td class=&quot;bold text-center border-sides-solid&quot; colspan=&quot;2&quot;&gt;
        ///					Notificação
        ///				&lt;/td&gt;
        ///			&lt;/tr&gt;
        ///
        ///			&lt;tr&gt;
        ///				&lt;td class=&quot;bold text-center border-sides-solid&quot; colspan=&quot;2&quot;&gt;
        ///					&lt;span&gt;Vimos por meio desta comunicar que o pedido de serviço de atualização de dados cadastrais foi deferido com base no art. 9 da Resolução n° 38, de 11 de maio de 2017 - CAS&lt;/span&gt;
        ///				&lt;/td&gt;
        ///			&lt;/t [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        public static string atualizacaoDadosCadastrais {
            get {
                return ResourceManager.GetString("atualizacaoDadosCadastrais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap brasao {
            get {
                object obj = ResourceManager.GetObject("brasao", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nenhum cadastro foi encontrado..
        /// </summary>
        public static string CADASTRO_NAO_ENCONTRADO {
            get {
                return ResourceManager.GetString("CADASTRO_NAO_ENCONTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cadastro realizado com sucesso..
        /// </summary>
        public static string CADASTRO_REALIZADO_COM_SUCESSO {
            get {
                return ResourceManager.GetString("CADASTRO_REALIZADO_COM_SUCESSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Campo não informado..
        /// </summary>
        public static string CAMPO_NAO_INFORMADO {
            get {
                return ResourceManager.GetString("CAMPO_NAO_INFORMADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Campo obrigatório não informado..
        /// </summary>
        public static string CAMPO_OBRIGATORIO_NAO_INFORMADO {
            get {
                return ResourceManager.GetString("CAMPO_OBRIGATORIO_NAO_INFORMADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {{&gt; style}}
        ///&lt;div class=&quot;text-center&quot; style=&quot;width:100%&quot;&gt;
        ///	&lt;table&gt;
        ///		&lt;tbody&gt;
        ///
        ///			{{&gt; notificacaoCabecalho}}
        ///
        ///			&lt;tr&gt;
        ///				&lt;td class=&quot;bold text-center border-sides-solid&quot; colspan=&quot;2&quot;&gt;
        ///					Notificação
        ///				&lt;/td&gt;
        ///			&lt;/tr&gt;
        ///
        ///			&lt;tr&gt;
        ///				&lt;td class=&quot;bold text-center border-sides-solid border-bottom-solid&quot; colspan=&quot;2&quot;&gt;
        ///					&lt;span&gt;Vimos por meio desta comunicar o CANCELAMENTO da Inscrição Cadastral, com base no § 1° do art. 36 da Resolução n° 38, de 11 de maio de 2017 - CAS, o recurso deverá ser interpo [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        public static string cancelamento {
            get {
                return ResourceManager.GetString("cancelamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {{&gt; style}}
        ///&lt;div class=&quot;text-center&quot; style=&quot;width:100%&quot;&gt;
        ///	&lt;table&gt;
        ///		&lt;tbody&gt;
        ///
        ///			{{&gt; notificacaoCabecalho}}
        ///
        ///			&lt;tr&gt;
        ///				&lt;td class=&quot;bold text-center border-sides-solid&quot; colspan=&quot;2&quot;&gt;
        ///					Notificação
        ///				&lt;/td&gt;
        ///			&lt;/tr&gt;
        ///
        ///			&lt;tr&gt;
        ///				&lt;td class=&quot;bold text-center border-sides-solid border-bottom-solid&quot; colspan=&quot;2&quot;&gt;
        ///					&lt;span&gt;Vimos por meio desta comunicar o CANCELAMENTO da Inscrição Cadastral, com base no inciso II do art. 32 da Resolução n° 38, de 11 de maio de 2017 - CAS. O recurso deverá ser in [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        public static string cancelamentoAguardandoRecurso {
            get {
                return ResourceManager.GetString("cancelamentoAguardandoRecurso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O captcha é inválido..
        /// </summary>
        public static string CAPTCHA_INVALIDO {
            get {
                return ResourceManager.GetString("CAPTCHA_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CEP inválido..
        /// </summary>
        public static string CEP_INVALIDO {
            get {
                return ResourceManager.GetString("CEP_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Este CEP já foi cadastrado..
        /// </summary>
        public static string CEP_JA_CADASTRADO {
            get {
                return ResourceManager.GetString("CEP_JA_CADASTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A chave precisa ser informada..
        /// </summary>
        public static string CHAVE_PRECISA_SER_INFORMADA {
            get {
                return ResourceManager.GetString("CHAVE_PRECISA_SER_INFORMADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CNPJ inválido..
        /// </summary>
        public static string CNPJ_INVALIDO {
            get {
                return ResourceManager.GetString("CNPJ_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Este CNPJ já foi adicionado..
        /// </summary>
        public static string CNPJ_JA_ADICIONADO {
            get {
                return ResourceManager.GetString("CNPJ_JA_ADICIONADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Já existe um cadastro para este CNPJ informado..
        /// </summary>
        public static string CNPJ_JA_CADASTRADO {
            get {
                return ResourceManager.GetString("CNPJ_JA_CADASTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Este CNPJ já possui credenciamento..
        /// </summary>
        public static string CNPJ_JA_CREDENCIADO {
            get {
                return ResourceManager.GetString("CNPJ_JA_CREDENCIADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CNPJ Já inscrito..
        /// </summary>
        public static string CNPJ_JA_INSCRITO {
            get {
                return ResourceManager.GetString("CNPJ_JA_INSCRITO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CNPJ já possui um credenciamento deste tipo.
        /// </summary>
        public static string CNPJ_JA_POSSUI_CREDENCIAMENTO_DESTE_TIPO {
            get {
                return ResourceManager.GetString("CNPJ_JA_POSSUI_CREDENCIAMENTO_DESTE_TIPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {{&gt; style}}
        ///&lt;div class=&quot;text-center&quot; style=&quot;width:100%&quot;&gt;
        ///	&lt;table&gt;
        ///		&lt;tbody&gt;
        ///
        ///			{{&gt; notificacaoCabecalho}}
        ///
        ///			&lt;tr&gt;
        ///				&lt;td class=&quot;bold text-center border-sides-solid&quot; colspan=&quot;2&quot;&gt;
        ///					Notificação
        ///				&lt;/td&gt;
        ///			&lt;/tr&gt;
        ///
        ///			&lt;tr&gt;
        ///				&lt;td class=&quot;bold text-center border-sides-solid&quot; colspan=&quot;2&quot;&gt;
        ///					&lt;span&gt;Vimos por meio desta comunicar que, após análise do pedido de serviço cadastral, &lt;u&gt;deverão ser apresentados os documentos originais abaixo listados a Unidade Cadastradora da SUFRAMA.&lt;/u&gt; Para re [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        public static string conferenciaAdministrativa {
            get {
                return ResourceManager.GetString("conferenciaAdministrativa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Confirma a exclusão?.
        /// </summary>
        public static string CONFIRMA_EXCLUSAO {
            get {
                return ResourceManager.GetString("CONFIRMA_EXCLUSAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Confirma a alteração?.
        /// </summary>
        public static string CONFIRMAR_ALTERACAO {
            get {
                return ResourceManager.GetString("CONFIRMAR_ALTERACAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Confirma a exclusão?.
        /// </summary>
        public static string CONFIRMAR_EXCLUSAO {
            get {
                return ResourceManager.GetString("CONFIRMAR_EXCLUSAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Confirma o novo cadastro?.
        /// </summary>
        public static string CONFIRMAR_NOVO_CADASTRO {
            get {
                return ResourceManager.GetString("CONFIRMAR_NOVO_CADASTRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Esta consulta exibe apenas protocolos de serviços cadastrais de “Inscrição Cadastral / Credenciamento”, para consultar protocolos dos demais serviços é necessário acessar o sistema por meio de login e senha..
        /// </summary>
        public static string CONSULTA_PROTOCOLO_NAO_PERMITIDO {
            get {
                return ResourceManager.GetString("CONSULTA_PROTOCOLO_NAO_PERMITIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {{&gt; style}}
        ///&lt;div class=&quot;text-center&quot; style=&quot;width:100%&quot;&gt;
        ///	&lt;table&gt;
        ///		&lt;tbody&gt;
        ///
        ///			{{&gt; notificacaoCabecalho}}
        ///
        ///			&lt;tr&gt;
        ///				&lt;td class=&quot;bold text-center border-sides-solid&quot; colspan=&quot;2&quot;&gt;
        ///					Notificação
        ///				&lt;/td&gt;
        ///			&lt;/tr&gt;
        ///
        ///			&lt;tr&gt;
        ///				&lt;td class=&quot;bold text-center border-sides-solid&quot; colspan=&quot;2&quot;&gt;
        ///					&lt;span&gt;Vimos por meio desta comunicar que, após análise do pedido de serviço cadastral, &lt;u&gt;foram identificadas pela SUFRAMA pendências no preenchimento do requerimento.&lt;/u&gt; As correções deverão ser envi [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        public static string correcaoInformacaoRequerimento {
            get {
                return ResourceManager.GetString("correcaoInformacaoRequerimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CPF inválido..
        /// </summary>
        public static string CPF_INVALIDO {
            get {
                return ResourceManager.GetString("CPF_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Este CPF já foi adicionado..
        /// </summary>
        public static string CPF_JA_ADICIONADO {
            get {
                return ResourceManager.GetString("CPF_JA_ADICIONADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Já existe um cadastro para este CPF informado.
        /// </summary>
        public static string CPF_JA_CADASTRADO {
            get {
                return ResourceManager.GetString("CPF_JA_CADASTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Este CPF já possui credenciamento..
        /// </summary>
        public static string CPF_JA_CREDENCIADO {
            get {
                return ResourceManager.GetString("CPF_JA_CREDENCIADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CPF já inscrito..
        /// </summary>
        public static string CPF_JA_INSCRITO {
            get {
                return ResourceManager.GetString("CPF_JA_INSCRITO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {{&gt; style}}
        ///&lt;div class=&quot;text-center&quot; style=&quot;width:100%&quot;&gt;
        ///	&lt;table&gt;
        ///		&lt;tbody&gt;
        ///
        ///			{{&gt; notificacaoCabecalho}}
        ///
        ///			&lt;tr&gt;
        ///				&lt;td class=&quot;bold text-center border-sides-solid&quot; colspan=&quot;2&quot;&gt;
        ///					Notificação
        ///				&lt;/td&gt;
        ///			&lt;/tr&gt;
        ///
        ///			&lt;tr&gt;
        ///				&lt;td class=&quot;bold text-center border-sides-solid&quot; colspan=&quot;2&quot;&gt;
        ///					&lt;span&gt;Vimos por meio desta comunicar que o pedido de serviço de credenciamento foi deferido com base no art. 9 da Resolução n° 38, de 11 de maio de 2017 - CAS.&lt;/span&gt;
        ///				&lt;/td&gt;
        ///			&lt;/tr&gt;
        ///
        ///			&lt;tr&gt;
        ///	 [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        public static string credenciamento {
            get {
                return ResourceManager.GetString("credenciamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Dado não encontrado..
        /// </summary>
        public static string DADO_NAO_ENCONTRADO {
            get {
                return ResourceManager.GetString("DADO_NAO_ENCONTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {{&gt; style}}
        ///&lt;div class=&quot;text-center&quot; style=&quot;width:100%&quot;&gt;
        ///	&lt;table&gt;
        ///		&lt;tbody&gt;
        ///
        ///			{{&gt; notificacaoCabecalho}}
        ///
        ///			&lt;tr&gt;
        ///				&lt;td class=&quot;bold text-center border-sides-solid&quot; colspan=&quot;2&quot;&gt;
        ///					Notificação
        ///				&lt;/td&gt;
        ///			&lt;/tr&gt;
        ///
        ///			&lt;tr&gt;
        ///				&lt;td class=&quot;bold text-center border-sides-solid border-bottom-solid&quot; colspan=&quot;2&quot;&gt;
        ///					&lt;span&gt;Vimos por meio desta comunicar que, após análise do pedido de atualização de dados cadastrais, o protocolo foi deferido com base no art. 9 da Resolução n° 38, de 11 de maio de [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        public static string deferimentoAtualizacaoDados {
            get {
                return ResourceManager.GetString("deferimentoAtualizacaoDados", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {{&gt; style}}
        ///&lt;div class=&quot;text-center&quot; style=&quot;width:100%&quot;&gt;
        ///	&lt;table&gt;
        ///		&lt;tbody&gt;
        ///
        ///			{{&gt; notificacaoCabecalho}}
        ///
        ///			&lt;tr&gt;
        ///				&lt;td class=&quot;bold text-center border-sides-solid&quot; colspan=&quot;2&quot;&gt;
        ///					Notificação
        ///				&lt;/td&gt;
        ///			&lt;/tr&gt;
        ///
        ///			&lt;tr&gt;
        ///				&lt;td class=&quot;bold text-center border-sides-solid border-bottom-solid&quot; colspan=&quot;2&quot;&gt;
        ///					&lt;span&gt;Vimos por meio desta comunicar que, após análise do pedido de serviço de atualização de documentos, o protocolo foi deferido com base no art. 9 da Resolução n° 38, de 11 de ma [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        public static string deferimentoAtualizacaoDocumentos {
            get {
                return ResourceManager.GetString("deferimentoAtualizacaoDocumentos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {{&gt; style}}
        ///&lt;div class=&quot;text-center&quot; style=&quot;width:100%&quot;&gt;
        ///	&lt;table&gt;
        ///		&lt;tbody&gt;
        ///
        ///			{{&gt; notificacaoCabecalho}}
        ///
        ///			&lt;tr&gt;
        ///				&lt;td class=&quot;bold text-center border-sides-solid&quot; colspan=&quot;2&quot;&gt;
        ///					Notificação de Deferimento
        ///				&lt;/td&gt;
        ///			&lt;/tr&gt;
        ///
        ///			&lt;tr&gt;
        ///				&lt;td class=&quot;bold text-center border-sides-solid&quot; colspan=&quot;2&quot;&gt;
        ///					&lt;span&gt;Vimos por meio desta comunicar que, após análise do pedido de serviço de credenciamento, o protocolo foi deferido com base no art. 9 da Resolução n° 38, de 11 de maio de 2017 - CAS [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        public static string deferimentoCredenciamento {
            get {
                return ResourceManager.GetString("deferimentoCredenciamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {{&gt; style}}
        ///&lt;div class=&quot;text-center&quot; style=&quot;width:100%&quot;&gt;
        ///	&lt;table&gt;
        ///		&lt;tbody&gt;
        ///
        ///			{{&gt; notificacaoCabecalho}}
        ///
        ///			&lt;tr&gt;
        ///				&lt;td class=&quot;bold text-center border-sides-solid&quot; colspan=&quot;2&quot;&gt;
        ///					Notificação de Deferimento
        ///				&lt;/td&gt;
        ///			&lt;/tr&gt;
        ///
        ///			&lt;tr&gt;
        ///				&lt;td class=&quot;bold text-center border-sides-solid&quot; colspan=&quot;2&quot;&gt;
        ///					&lt;span&gt;Vimos por meio desta comunicar que, após análise do pedido de serviço cadastral, o protocolo foi deferido com base no art. 9 da Resolução n° 38, de 11 de maio de 2017 - CAS.&lt;/span&gt; [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        public static string deferimentoInscricaoCadastral {
            get {
                return ResourceManager.GetString("deferimentoInscricaoCadastral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {{&gt; style}}
        ///&lt;div class=&quot;text-center&quot; style=&quot;width:100%&quot;&gt;
        ///	&lt;table&gt;
        ///		&lt;tbody&gt;
        ///
        ///			{{&gt; notificacaoCabecalho}}
        ///
        ///			&lt;tr&gt;
        ///				&lt;td class=&quot;bold text-center border-sides-solid&quot; colspan=&quot;2&quot;&gt;
        ///					Notificação
        ///				&lt;/td&gt;
        ///			&lt;/tr&gt;
        ///
        ///			&lt;tr&gt;
        ///				&lt;td class=&quot;bold text-center border-sides-solid&quot; colspan=&quot;2&quot;&gt;
        ///					&lt;span&gt;Vimos por meio desta comunicar que, após análise do pedido de serviço de reativação, o protocolo foi deferido com base no art. 9 da Resolução n° 38, de 11 de maio de 2017 - CAS.&lt;/span&gt;
        ///				&lt;/td&gt; [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        public static string deferimentoReativacao {
            get {
                return ResourceManager.GetString("deferimentoReativacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Esta atividade já foi incluída..
        /// </summary>
        public static string ESTA_ATIVIDADE_JA_FOI_INCLUIDA {
            get {
                return ResourceManager.GetString("ESTA_ATIVIDADE_JA_FOI_INCLUIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Operação não realizada. Este registro foi modificado por outro usuário. Realize a consulta novamente..
        /// </summary>
        public static string ESTE_REGISTRO_NAO_PODE_SER_ALTERADO {
            get {
                return ResourceManager.GetString("ESTE_REGISTRO_NAO_PODE_SER_ALTERADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Exclusão não realizada. Este registro já foi removido. .
        /// </summary>
        public static string ESTE_REGISTRO_NAO_PODE_SER_EXCLUIDO {
            get {
                return ResourceManager.GetString("ESTE_REGISTRO_NAO_PODE_SER_EXCLUIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Exclusão realizada com sucesso..
        /// </summary>
        public static string EXCLUSAO_REALIZADA_COM_SUCESSO {
            get {
                return ResourceManager.GetString("EXCLUSAO_REALIZADA_COM_SUCESSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Favor selecionar um arquivo no formato PDF..
        /// </summary>
        public static string FAVOR_SELECIONAR_UM_ARQUIVO_NO_FORMADO_PDF {
            get {
                return ResourceManager.GetString("FAVOR_SELECIONAR_UM_ARQUIVO_NO_FORMADO_PDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Por favor, tente imprimir a GRU referente ao pagamento da taxa de serviço dentro de alguns instantes no link abaixo: http://www4.suframa.gov.br/arrecadacao/gru/gru_reimpressao.aspx.
        /// </summary>
        public static string IMPRIMIR_GRU_EM_INSTANTES {
            get {
                return ResourceManager.GetString("IMPRIMIR_GRU_EM_INSTANTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {{&gt; style}}
        ///&lt;div class=&quot;text-center&quot; style=&quot;width:100%&quot;&gt;
        ///	&lt;table&gt;
        ///		&lt;tbody&gt;
        ///
        ///			{{&gt; notificacaoCabecalho}}
        ///
        ///			&lt;tr&gt;
        ///				&lt;td class=&quot;bold text-center border-sides-solid&quot; colspan=&quot;2&quot;&gt;
        ///					Notificação de Indeferimento
        ///				&lt;/td&gt;
        ///			&lt;/tr&gt;
        ///
        ///			&lt;tr&gt;
        ///				&lt;td class=&quot;bold text-center border-sides-solid&quot; colspan=&quot;2&quot;&gt;
        ///					&lt;span&gt;Vimos por meio desta comunicar que, após análise do pedido de serviço cadastral, o protocolo foi indeferido com base no art. 24 da Resolução n° 38, de 11 de maio de 2017 - CAS. O [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        public static string indeferimento {
            get {
                return ResourceManager.GetString("indeferimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;b style=&quot;color:#00552b&quot;&gt;CAROS USUÁRIOS&lt;/b&gt;, Para &lt;b style=&quot;color:#00552b&quot;&gt;CADA TIPO&lt;/b&gt; de &lt;b style=&quot;color:#00552b&quot;&gt;DOCUMENTO COMPROBATÓRIO&lt;/b&gt; exigido na solicitação de Inscrição Cadastral ou Credenciamento deverá ser anexado um &lt;b style=&quot;color:#00552b&quot;&gt;ÚNICO&lt;/b&gt; arquivo PDF. O documento comprovante de domicílio na solicitação de &lt;b style=&quot;color:#00552b&quot;&gt;INSCRIÇÃO CADASTRAL DE PESSOA JURÍDICA&lt;/b&gt; deverá ser o &lt;b style=&quot;color:#00552b&quot;&gt;CONTRATO DE LOCAÇÃO, ESCRITURA PUBLICA, CERTIDÃO DO CARTÓRIO DE IMOVEIS, [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        public static string INFORMATIVO_PRIMEIRO_ACESSO {
            get {
                return ResourceManager.GetString("INFORMATIVO_PRIMEIRO_ACESSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A inscrição cadastral não encontra-se inativa para realizar uma Reativação. É necessário estar inativa para isto..
        /// </summary>
        public static string INSCRICAO_CADASTRAL_NAO_ENCONTRASE_INATIVA_PARA_REALIZAR_UMA_REATIVACAO {
            get {
                return ResourceManager.GetString("INSCRICAO_CADASTRAL_NAO_ENCONTRASE_INATIVA_PARA_REALIZAR_UMA_REATIVACAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Falha na comunicação. Tente mais tarde..
        /// </summary>
        public static string LEGADO_ERRO_COMUNICACAO {
            get {
                return ResourceManager.GetString("LEGADO_ERRO_COMUNICACAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Já existe uma unidade principal cadastrada para esse município..
        /// </summary>
        public static string MUNICIPIO_JA_CADASTRADO {
            get {
                return ResourceManager.GetString("MUNICIPIO_JA_CADASTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não há uma Inscrição Cadastral ativa para este CPF/CNPJ.
        /// </summary>
        public static string NAO_POSSUI_INSCRICAO_CADASTRAL_ATIVA {
            get {
                return ResourceManager.GetString("NAO_POSSUI_INSCRICAO_CADASTRAL_ATIVA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nenhum cadastro foi encontrado..
        /// </summary>
        public static string NENHUM_CADASTRO_FOI_ENCONTRADO {
            get {
                return ResourceManager.GetString("NENHUM_CADASTRO_FOI_ENCONTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nenhum documento foi adicionado..
        /// </summary>
        public static string NENHUM_DOCUMENTO_ADICIONADO {
            get {
                return ResourceManager.GetString("NENHUM_DOCUMENTO_ADICIONADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nenhum protocolo foi encontrado..
        /// </summary>
        public static string NENHUM_PROTOCOLO_FOI_ENCONTRADO {
            get {
                return ResourceManager.GetString("NENHUM_PROTOCOLO_FOI_ENCONTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;tr class=&quot;text-center&quot;&gt;
        ///	&lt;td colspan=&quot;2&quot;&gt;
        ///		&lt;img src=&quot;data:image/gif;base64,R0lGODlhZABjAPcAAK2srBmItQFql9a2TJ4cFd0iIgRwMQQrTvzwK/DRLBERDtSzAgFurm9ubQgjKiV1RAhPJSQmKrKRA45wA4xzWtfNBCpvkvbvS0ktAta1LWxPAlJRTvDXSyVMLdnRTQRKcLSuAu+7MFBIA+ysqHJqApSMAw4RJyIRIwFIELeuS7GUSbCTK9rQKydQbSp5rgJSjY1yMw92QE9IKXJqLGpRKbauKydKTZWLLJWNSEksJgd2yu4iEG1oTiNmO0wBAs6XAs7Mu0dukHMqJmdUUfPb2SlndIiIdncEAQlGUYZ3feNoaO7u3dnSadkRD6x2ASaGyiKIR+4iIvDaaHeIdmkvBKyZmL6ua9cRI+4REPPuZ8y7v3eIiLrNBg5mgayqmYlUAFJTaO4RIihUineIEPDd77mSbd3uBNzvT [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        public static string notificacaoCabecalho {
            get {
                return ResourceManager.GetString("notificacaoCabecalho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O número CNPJ precisa ser informado..
        /// </summary>
        public static string NUMERO_CNPJ_PRECISA_SER_INFORMADO {
            get {
                return ResourceManager.GetString("NUMERO_CNPJ_PRECISA_SER_INFORMADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Operação realizada com sucesso..
        /// </summary>
        public static string OPERACAO_REALIZADA_COM_SUCESSO {
            get {
                return ResourceManager.GetString("OPERACAO_REALIZADA_COM_SUCESSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Para realizar uma consulta informe pelo menos um dos parâmetros..
        /// </summary>
        public static string PARA_REALIZAR_UMA_CONSULTA_INFORME_PELO_MENOS_UM_DOS_PARAMETROS {
            get {
                return ResourceManager.GetString("PARA_REALIZAR_UMA_CONSULTA_INFORME_PELO_MENOS_UM_DOS_PARAMETROS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///	&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot; /&gt;
        ///	&lt;title&gt;SUFRAMA&lt;/title&gt;
        ///	&lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot; /&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///	&lt;table align=&quot;center&quot; border=&quot;1&quot; cellpadding=&quot;0&quot; cellspacing=&quot;0&quot; width=&quot;600&quot;&gt;
        ///		&lt;tr&gt;
        ///			&lt;td align=&quot;center&quot; style=&quot;padding: 10px 0 10px 0;&quot;&gt;
        ///			 [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        public static string paridadeCambial {
            get {
                return ResourceManager.GetString("paridadeCambial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Identificação de pessoa fisica não informada..
        /// </summary>
        public static string PESSOA_FISICA_NAO_INFORMADA {
            get {
                return ResourceManager.GetString("PESSOA_FISICA_NAO_INFORMADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Esse CNPJ/CPF não possui acesso ao novo sistema de cadastro. Você será redirecionado para o link de Primeiro Acesso ao SCIEX..
        /// </summary>
        public static string PESSOA_INEXISTENTE {
            get {
                return ResourceManager.GetString("PESSOA_INEXISTENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Identificação de pessoa juridica não informada..
        /// </summary>
        public static string PESSOA_JURIDICA_NAO_INFORMADA {
            get {
                return ResourceManager.GetString("PESSOA_JURIDICA_NAO_INFORMADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;style&gt;
        ///	table {
        ///		width: 100%;
        ///		font-family: &apos;Segoe UI&apos;;
        ///	}
        ///
        ///	tr {
        ///		height: 25px;
        ///	}
        ///
        ///	.bold {
        ///		font-weight: bold;
        ///	}
        ///
        ///	.padding-top {
        ///		padding-top: 10px;
        ///	}
        ///
        ///	.text-center {
        ///		text-align: center !important;
        ///	}
        ///
        ///	.border-bottom-dashed {
        ///		border-bottom: 1px dashed #000;
        ///	}
        ///
        ///	.border-bottom-solid {
        ///		border-bottom: 2px solid #000;
        ///	}
        ///
        ///	.border-top-solid {
        ///		border-top: 2px solid #000;
        ///	}
        ///
        ///	.font-size-lg {
        ///		font-size: 34px;
        ///	}
        ///
        ///	.height-lg {
        ///		height: 70px;
        ///	}
        ///
        /// [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        public static string protocolo {
            get {
                return ResourceManager.GetString("protocolo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;div id=&quot;container&quot; class=&quot;template container border&quot; style=&quot;max-width: 790px;&quot;&gt;
        ///	&lt;style type=&quot;text/css&quot; scoped&gt;
        ///		.template {
        ///			border: 0;
        ///			box-sizing: border-box;
        ///			font-family: &apos;Segoe UI&apos;;
        ///			font-size: 13px;
        ///			margin: 0;
        ///			padding: 0;
        ///			vertical-align: baseline;
        ///		}
        ///
        ///		.container {
        ///			margin: 0 auto;
        ///			width: 100%;
        ///		}
        ///
        ///		.container:before,
        ///		.container:after,
        ///		.row:before,
        ///		.row:after {
        ///			content: &quot;&quot;;
        ///			display: table;
        ///		}
        ///
        ///		.container:after,
        ///		.row:after {
        ///			cl [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        public static string protocoloAgendaAtendimento {
            get {
                return ResourceManager.GetString("protocoloAgendaAtendimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;style&gt;
        ///	* {
        ///		border: 0;
        ///		box-sizing: border-box;
        ///		font-family: &apos;Segoe UI&apos;;
        ///		font-size: 13px;
        ///		margin: 0;
        ///		padding: 0;
        ///		vertical-align: baseline;
        ///	}
        ///
        ///	.container {
        ///		margin: 0 auto;
        ///		padding: 0 1rem;
        ///		width: 100%;
        ///	}
        ///
        ///		.container:before, .container:after, .row:before, .row:after {
        ///			content: &quot; &quot;;
        ///			display: table;
        ///		}
        ///
        ///		.container:after, .row:after {
        ///			clear: both;
        ///		}
        ///
        ///	.row {
        ///		margin: 1rem 0;
        ///		width: 100%;
        ///	}
        ///
        ///	.col, .col-1, .col-2, .col-3, .col-4, .col-5, .c [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        public static string protocoloSituacaoCadastral {
            get {
                return ResourceManager.GetString("protocoloSituacaoCadastral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Registro duplicado, não pode ser inserido..
        /// </summary>
        public static string REGISTRO_DUPLICADO {
            get {
                return ResourceManager.GetString("REGISTRO_DUPLICADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O código da Natureza Jurídica já foi cadastrado..
        /// </summary>
        public static string REGISTRO_JA_EXISTENTE {
            get {
                return ResourceManager.GetString("REGISTRO_JA_EXISTENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Exclusão não realizada. Item está associado a outro registro do sistema..
        /// </summary>
        public static string RELACIONAMENTO_EXISTE {
            get {
                return ResourceManager.GetString("RELACIONAMENTO_EXISTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Este representante da entidade já foi cadastrado..
        /// </summary>
        public static string REPRESENTANTE_ENTIDADE_JA_CADASTRADO {
            get {
                return ResourceManager.GetString("REPRESENTANTE_ENTIDADE_JA_CADASTRADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Este representante da entidade já foi cadastrado..
        /// </summary>
        public static string REPRESENTANTE_JA_EXISTENTE {
            get {
                return ResourceManager.GetString("REPRESENTANTE_JA_EXISTENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Existe requerimento associado..
        /// </summary>
        public static string REQUERIMENTO_EXISTENTE {
            get {
                return ResourceManager.GetString("REQUERIMENTO_EXISTENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Serviço indisponível, tente novamente mais tarde..
        /// </summary>
        public static string SERVICO_INDISPONIVEL {
            get {
                return ResourceManager.GetString("SERVICO_INDISPONIVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sua sessão expirou. Faça login novamente no sistema..
        /// </summary>
        public static string SESSAO_EXPIRADA {
            get {
                return ResourceManager.GetString("SESSAO_EXPIRADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Setor já cadastrado na base de dados da Suframa..
        /// </summary>
        public static string SETOR_JA_EXISTENTE {
            get {
                return ResourceManager.GetString("SETOR_JA_EXISTENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Seu usuário não possui perfil atribuído ao sistema CADSUF. Comunique o coordenador de sua área..
        /// </summary>
        public static string SEU_USUARIO_NAO_POSSUI_PERFIL_ATRIBUIDO_AO_SISTEMA_CADSUF_COMUNIQUE_O_COORDENADOR_DE_SUA_AREA {
            get {
                return ResourceManager.GetString("SEU_USUARIO_NAO_POSSUI_PERFIL_ATRIBUIDO_AO_SISTEMA_CADSUF_COMUNIQUE_O_COORDENADOR" +
                        "_DE_SUA_AREA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &lt;style&gt;
        ///	table {
        ///		width: 80%;
        ///		font-family: &apos;Segoe UI&apos;;
        ///		margin: 0 auto;
        ///		border-spacing: 0;
        ///		border-collapse: collapse;
        ///	}
        ///
        ///	tr {
        ///		height: 25px;
        ///	}
        ///
        ///	.bold {
        ///		font-weight: bold;
        ///	}
        ///
        ///	.padding-top {
        ///		padding-top: 10px;
        ///	}
        ///
        ///	.text-center {
        ///		text-align: center !important;
        ///	}
        ///
        ///	.text-left {
        ///		text-align: left !important;
        ///	}
        ///
        ///	.text-right {
        ///		text-align: right !important;
        ///	}
        ///
        ///	.border-bottom-dashed {
        ///		border-bottom: 1px dashed #000;
        ///	}
        ///
        ///	.border-bottom-solid {
        ///		b [o restante da cadeia de caracteres foi truncado]&quot;;.
        /// </summary>
        public static string style {
            get {
                return ResourceManager.GetString("style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Código de Subclasse já cadastrado na base de dados da Suframa..
        /// </summary>
        public static string SUBCLASSE_JA_EXISTENTE {
            get {
                return ResourceManager.GetString("SUBCLASSE_JA_EXISTENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Subclasse já cadastrada para este setor..
        /// </summary>
        public static string SUBLCASSE_JA_CADASTRADA_PARA_ESTE_SETOR {
            get {
                return ResourceManager.GetString("SUBLCASSE_JA_CADASTRADA_PARA_ESTE_SETOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O Documento para ser anexado deve conter no máximo 20 MB.
        /// </summary>
        public static string TAMANHO_DOCUMENTO_INVALIDO {
            get {
                return ResourceManager.GetString("TAMANHO_DOCUMENTO_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Já foi adicionado um documento para este tipo de documento..
        /// </summary>
        public static string TIPO_DOCUMENTO_JA_ADICIONADO {
            get {
                return ResourceManager.GetString("TIPO_DOCUMENTO_JA_ADICIONADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Este tipo de requerimento não gera protocolo..
        /// </summary>
        public static string TIPO_REQUERIMENTO_NAO_GERA_PROTOCOLO {
            get {
                return ResourceManager.GetString("TIPO_REQUERIMENTO_NAO_GERA_PROTOCOLO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Já existe uma unidade principal cadastrada para esse município..
        /// </summary>
        public static string UNIDADE_JA_CADASTRADA {
            get {
                return ResourceManager.GetString("UNIDADE_JA_CADASTRADA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Seu usuário não possui perfil atribuído ao sistema CADSUF. Comunique o coordenador de sua área..
        /// </summary>
        public static string USUARIO_INTERNO_INEXISTENTE {
            get {
                return ResourceManager.GetString("USUARIO_INTERNO_INEXISTENTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O analista já foi incluído anteriormente..
        /// </summary>
        public static string USUARIO_INTERNO_JA_INCLUIDO {
            get {
                return ResourceManager.GetString("USUARIO_INTERNO_JA_INCLUIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário não pode ser excluído, pois não existe outro usuário com o mesmo papel na listagem..
        /// </summary>
        public static string USUARIO_NAO_PODE_SER_EXCLUIDO {
            get {
                return ResourceManager.GetString("USUARIO_NAO_PODE_SER_EXCLUIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Usuário não pode ser inativado, pois não existe outro usuário com o mesmo papel na listagem..
        /// </summary>
        public static string USUARIO_NAO_PODE_SER_INATIVADO {
            get {
                return ResourceManager.GetString("USUARIO_NAO_PODE_SER_INATIVADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Login ou senha inválido..
        /// </summary>
        public static string USUARIO_SENHA_INVALIDOS {
            get {
                return ResourceManager.GetString("USUARIO_SENHA_INVALIDOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Validar o campo {0}..
        /// </summary>
        public static string VALIDAR_CAMPO {
            get {
                return ResourceManager.GetString("VALIDAR_CAMPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Você não pode editar uma diligência já finalizada..
        /// </summary>
        public static string VOCE_NAO_PODE_EDITAR_UMA_DILIGENCIA_JA_FINALIZADA {
            get {
                return ResourceManager.GetString("VOCE_NAO_PODE_EDITAR_UMA_DILIGENCIA_JA_FINALIZADA", resourceCulture);
            }
        }
    }
}
